### ISSUE TITLE
Error while training new data

### ISSUE THREAD

**Issue by heitorsampaio** [Caff1982/football-predictions#2]
Hey Caff,

I'm facing this error 'ValueError: Error when checking input: expected dense_22_input to have shape (38,) but got array with shape (34,)' while trying to train new data with the past games.

the only trained data that works is yours from 25Nov19, looks like the data shape is getting wrong in the training script, the script collect 38 columns as usual, but the predict script just read 34, don't know why, i tried to change the columns but got not success.

Do you know why this is happening? 

Cheers!

**Comment by Caff1982** [comment]
Hi,

I changed the features slightly and must have forgot to update it. The columns I dropped were the half-time goal stats: 'f_halfTimeGoalsAgainstHome', 'f_halfTimeGoalsForHome, 'f_halfTimeGoalsAgainstAway' and 'f_halfTimeGoalsForAway'. If you drop those it should work. 

Also to let you know, I found a problem with the data. The predictions didn't match what the model predicted, this was because there was a data-leak. The goal stats (ie: HTGS, ATGS, etc) in the data were for that current game, they should have been shifted back one like with the EMA stats, otherwise it is impossible to make accurate future predictions.

Sorry about that! I'm still working on updating this, I'm not able to get quite the same accuracy as before but still a bit ahead of the bookies accuracy. If you have any suggestions please don't hesitate to contact me.

Cheers,
